name: Deploy to Nginx (GCE)

on:
  push:
    branches:
      - main

env:
  # -------------------------------------------------------
  # CONFIGURATION
  # -------------------------------------------------------
  GCE_INSTANCE: 'web'   # Replace with your VM Name
  GCE_ZONE: 'us-east1-c '       # Replace with your VM Zone
  SOURCE_DIR: './'                # Use './' for root, or './dist' if building a React/Vue app
  TARGET_DIR: '/var/www/html'     # Standard Nginx web root
  # -------------------------------------------------------

jobs:
  deploy-to-vm:
    runs-on: ubuntu-latest
    environment: SSH_GT
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # 1. Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Authenticate with Google Cloud
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 3. Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: qwiklabs-gcp-02-a513cc6b7e45 

      # 4. Deploy Strategy (SCP -> SSH Move)
      - name: Deploy Files
        run: |
          echo "🚧 Starting Deployment to $GCE_INSTANCE..."

          # A. Clean up temp folder on VM (Idempotency check)
          # We use --command to run shell commands remotely
          gcloud compute ssh $GCE_INSTANCE --zone=$GCE_ZONE --command "rm -rf ~/deploy-temp"

          # B. Upload files to User Home (The only place we have write access initially)
          echo "📦 Uploading files to temporary storage..."
          gcloud compute scp --recurse $SOURCE_DIR $GCE_INSTANCE:~/deploy-temp --zone=$GCE_ZONE

          # C. Sudo Move and Restart Nginx
          # We chain commands with && to ensure they happen in order
          echo "🚀 Moving files to Nginx root and reloading..."
          gcloud compute ssh $GCE_INSTANCE --zone=$GCE_ZONE --command "\
            sudo rm -rf $TARGET_DIR/* && \
            sudo cp -r ~/deploy-temp/* $TARGET_DIR/ && \
            sudo chown -R www-data:www-data $TARGET_DIR && \
            sudo chmod -R 755 $TARGET_DIR && \
            sudo systemctl reload nginx && \
            rm -rf ~/deploy-temp"

          echo "✅ Deployment Successful!"
